In [1]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix


In [2]:
# Load your data into a pandas dataframe
data = pd.read_csv('features.csv',index_col=0)
data = data[~data.isnull().any(axis=1)]

In [3]:
# Split the data into training and testing sets
train, test = train_test_split(data, test_size=0.2, random_state=42)


# Separate the target variable from the input features
X_train = train.drop('OUTCOMETYPE', axis=1)
y_train = train['OUTCOMETYPE']

X_test = test.drop('OUTCOMETYPE', axis=1)
y_test = test['OUTCOMETYPE']

cols = X_train.columns


In [4]:
# Scale the input features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [5]:
# Instantiate the Random Forest Classifier model
rfc = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=99)

In [6]:
# Instantiate the Gradient Boosting Classifier model
gbc = GradientBoostingClassifier(n_estimators=100, max_depth=3, learning_rate=0.1, random_state=99)

In [7]:
# Instantiate the Support Vector Method Classifier model
svm = SVC(kernel='linear', C=1.0, random_state=99)

In [8]:
# Instantiate a voting classifier model as an emsemble of the above three models  
model = VotingClassifier(estimators=[('rf', rfc), ('gb', gbc), ('svm', svm)], voting='hard')

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict the classes of test data
y_pred = model.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.89


In [9]:
# Print the confusion matrix
print("\n")
print("-------------------------------------------------------------")
print("Confusion Matrix:")
print("-----------------")
print(confusion_matrix(y_test, y_pred))

# Print the classification report
print("\n")
print("-------------------------------------------------------------")
print("Classification Report:")
print("------------------------")
rpt =classification_report(y_test, y_pred, output_dict=False)
print(rpt)





-------------------------------------------------------------
Confusion Matrix:
-----------------
[[6209    0  143]
 [ 236   20  101]
 [ 647    1 2759]]


-------------------------------------------------------------
Classification Report:
------------------------
              precision    recall  f1-score   support

       ADOPT       0.88      0.98      0.92      6352
        DIED       0.95      0.06      0.11       357
         RTO       0.92      0.81      0.86      3407

    accuracy                           0.89     10116
   macro avg       0.92      0.61      0.63     10116
weighted avg       0.89      0.89      0.87     10116

